Updates NH and CC details
UCSD-E4E/website pull request #25
Opened 2023-07-03 18:49 UTC by HJGrant

2023-07-06 19:49 UTC, ntlhui requested changes

2023-07-06 19:49 UTC, ntlhui commented on people/people.yml
> +  Level: Project Member
This should be `level`, not `Level`.

2023-07-06 19:50 UTC, ntlhui commented
Also, please resolve conflicts and change the pull request title to accurately reflect the changes.

2023-07-07 03:50 UTC, HJGrant reviewed
I corrected the typo.

2023-07-07 04:39 UTC, ntlhui submitted a review, later dismissed

2023-07-07 04:42 UTC, merged