Update publications.bib
UCSD-E4E/website pull request #4
Opened 2021-12-14 23:22 UTC by JacobGlennAyers

Added in the recent automated acoustic species identification publication: https://www.climatechange.ai/papers/neurips2021/56

2021-12-15 01:38 UTC, ntlhui requested changes
Please follow the naming convention as specified in the readme

2021-12-15 01:38 UTC, ntlhui commented on publications/publications.bib
> +@inproceedings{ayers2021reducing,
Please follow the naming convention as set out in https://github.com/UCSD-E4E/website/blob/master/publications/README.md.

Replicated here:

Set the BibTeX key as follows: first three last names separated by underscores, followed by "et al" if more than three authors, followed by the abbreviated journal/conference/publisher, followed by the year. If more than one entry matches the same key, suffix this with "_2" for the second publication, "_3" for the third, and so on.

2021-12-19 01:40 UTC, JacobGlennAyers reviewed
I modified ayers2021reducing to ayers_perry_tiwari_et_al_neurips_2021 and moved this publication down to the bottom of the officially published works. I believe that is all that was required by the readme.

2021-12-19 02:09 UTC, ntlhui approved these changes

2021-12-19 02:09 UTC, merged